version: '3'
services:
  app:
    build: ./docker/php
    container_name: alex_l01_app
    volumes:
      - ./:/var/www
  apache:
    build: './docker/httpd'
    depends_on:
      - app
    ports:
      - "80:80"